
GET http://localhost:3000/api/tasks

###

POST http://localhost:3000/api/tasks
Content-Type: application/json

{
    "title": "Tengo que hacer un sitio en angular",
    "description": "trabajo freelance"
}